### ISSUE TITLE
several compilation problems

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#100]
1) in lumina-finelinfo: 
ui_dialog.h:94: error: 'class QTabWidget' has no member named 'setTabBarAutoHide'
I think this is due to the fact that you are using QT5.4; which is not yet packaged on all platforms

2) in lumina-fm:
MainUI.cpp:1011: error: no matching function for call to 'LUtils::isFavorite(QFileInfo&)'
../libLumina/LuminaUtils.h:53: note: candidates are: static bool LUtils::isFavorite(QString)
Does it compile on your system ?

3) in lumina-wm
Failure to find: WMSession.cpp
missing git add ?

**Comment by beanpole135** [comment]
Sorry about that!
1) I was not aware that option for the QTabWidget was new as of Qt 5.4 - I just removed that line for the moment, so when OpenBSD gets Qt 5.4, please let me know since that option just makes things look/feel a lot better.

2) I was actually in the middle of changes to that utility and got interrupted last night - sorry! It is all back to working order now.

3) The "lumina-wm" directory/project is highly incomplete and is not tied into the general build procedures for Lumina at the present time. That project will not be going "live" until Lumina 0.9.0, and until that time Lumina will continue to use Fluxbox for window management.

**Comment by william-os4y** [comment]
1) The doc says that setTabBarAutoHide was dded in QT5.4.
OpenBSD-current has just, since April 19th, has moved to 5.4.1.  In other
words, this could be added in the next release, thus 5.8 (5.7 is already
packaged).
But, if I look at Debian, they are still using 5.3.2 on their stable
platform.
https://packages.debian.org/search?keywords=qt5&searchon=names&suite=stable&section=all


2) Maybe a "bad" habbit on my side. In Openbsd they don't push
untested/uncomplete code.
No, I know ... But, then, when should I report compilation error ?
How to know if the error I have is "new" for you ?


3) Since my global compilation was failing, I did it per folder.
I did not noticed that lumina-wm was not in the general build. No, I know.

**Comment by beanpole135** [comment]
1) Yeah, it is not a problem if I hold off on it a little bit. As I mentioned, it is just a minor visual change - nothing too serious.
2) I try to do the same thing: I just got sloppy yesterday.... :-(
3) Yeah, I am going to put something on that directory to mark it as "Broken/untested" here really soon. That should help prevent this from happening again...
