### ISSUE TITLE
Would it be difficult to have xclock as desktop plugin ?

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#102]
I think that xclock is present on all platforms. So because some person like the analog clock, it could be funny to have it. 

This could be complementary to the taskbar digital clock

Many thanks

**Comment by beanpole135** [comment]
Unfortunately, the desktop plugin system requires a Qt-based plugin implementation, rather than just embedding another utility like xclock. However, I think the idea of an analog clock for the desktop is a great idea! While there is not a pre-defined analog clock widget within Qt, one of the Qt coding examples[1] details how to create one using the QPainter class. This might provide a good starting point if you want to start putting one together... :-)

[1] http://doc.qt.io/qt-5/qtwidgets-widgets-analogclock-example.html

**Comment by william-os4y** [comment]
In fact, by launching xclock via the auto-start AND by using the fluxbox features of the xclock window (remember position, remember dimensions, and remember layer with layer bottom) this fit perfectly my needs. 

To be perfect it would be great to remove the borders.

**Comment by beanpole135** [comment]
There might be a way to tell Fluxbox not to paint the frame on that window through the ~/.fluxbox/apps config file. I am not sure however, since that is delving into more complicated Fluxbox configs than I am used to... :-)

**Comment by william-os4y** [comment]
Thanks to fluxbox this is really easy and do the following:
- close the xclock application (in case you have flagged "save on close", because this will overwrite your changes). 
- edit the .fluxbox/apps file and add/change the [Deco] parameter to {NONE}.
- start xclock, and that's it. 

Here after my complete config for xclock:
```
[app] (name=xclock) (class=XClock)
  [Dimensions]  {10% 15%}
  [Position]    (UPPERLEFT)     {86% 0%}
  [Deco]        {NONE}
  [Layer]       {10}
  [Close]       {yes}
[end]
```

**Comment by beanpole135** [comment]
Glad you figured that out!
