### ISSUE TITLE
window properties issue in lumina-config

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#107]
To reproduce the problem you have to do the following in lumina-config:
- "Apparance -> Theme template" click on Edit
- since this screen allow you to edit the config file, resize the window
- right click on title bar 
- select "remember ..." -> dimensions
- select "remember ..." -> save on close
- close the window (no need to perform changes in the config)
```
Now each tie you will edit this config you will get a perfect 
screen allowing you to see and update easily the parameters.
```
- Go to "Application -> File Defaults"
- click on "xterm". 
```
==> you should have a big screen as it was set in the "Theme template Edit". 
Unfortunately in this cas this is to show a dropdown with 3 buttons. 
```
Sounds that for Fluxbox those 2 screens are the same. 
But, from user point of view, they are not.

**Comment by beanpole135** [comment]
This sounds like Fluxbbox being unable to distinguish between different child windows of a single parent (lumina-config in this case). In the situation your are describing, the two windows have different _NET_WM_NAME values, so they *should* be distinct from each other in the fluxbox window-matching routines (you can see the entry for it in ~/.fluxbox/apps).
This might be something to bring up with the Fluxbox developers, see if they know about it or already have a fix for it.
I just tracked down the Fluxbox config file

**Comment by william-os4y** [comment]
Are you able to reproduce it ?

**Comment by beanpole135** [comment]
Yes, I was able to reproduce it on FreeBSD, and it is any combination of child windows that causes this effect. If you look in the Fluxbox "apps" file, you can see that there are two identifiers used for a window in that file, but both of them turn out to be the WM_CLASS value, which is application-specific and not window-specific. This is why I think it needs to be brought up with the Fluxbox developers, because you may have found a bug in their window identification routines.
