### ISSUE TITLE
Where are autostarted applications stored?

### ISSUE THREAD

**Issue by crossroads1112** [pcbsd/lumina#116]
When I enable a binary to be autostarted, where does lumina store this information?

**Comment by beanpole135** [comment]
Right now Lumina is in a state of flux for the location of auto-started applications.
As of 0.8.4, it uses read/write of the ~/.lumina/startapps file  on a per-user basis (one command per line - this is where things are currently being saved), but it also has read-only abilities for the XDG autostart specifications (`/usr/local/etc/xdg/autostart/*.desktop` or `~/.config/autostart/*.desktop` on FreeBSD).
I am working on moving completely over to the XDG specifications here in the very near future, the only major hold-up is that I have not gotten the old->new format conversion routine written up yet (since I want the transition to be as seamless as possible for current users).

**Comment by beanpole135** [comment]
FYI: In just finished up the conversion to using the the XDG autostart specs fully for Lumina 0.8.5 and onward. If you build from sources, you will get these new changes immediately.
