### ISSUE TITLE
Lumina wallpaper cannot be removed

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#122]
System is always placing a picture. 
It's not possible to use the fluxbox background.

**Comment by beanpole135** [comment]
This is by design.
The X server/display does not understand the concept of multiple monitors or divisions in the graphical output, so it has a single "root" window which is underneath everything. Fluxbox paints it's background onto this root window, but in multiple-monitor situations that results in major graphical stretching/distortion because of the lack of boundaries and separation between the outputs. 
Lumina (and most other DE's) take the approach of providing "virtual root" windows (one per monitor), which overlay the primary root window and provide the necessary separation defined by the output settings. These virtual root windows are registered on the system through the FreeDesktop specifications (_NET_VIRTUAL_ROOTS) so applications know that the system-root window is non-visible and should act accordingly.
