### ISSUE TITLE
Transparency is linked to the fluxbox background (not lumina brancground)

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#123]
I was surprised that the transparency was not working. But in fact the transparency works with the fluxbox background. 

To reproduce the problem, assign a picture to the fluxbox background and change the transparency parameter of one window (Eterm is nice for that). The picture on the background of fluxbox appears.

**Comment by beanpole135** [comment]
This is a known issues because Fluxbox does not provide compositing between windows. This results in every window/application using the "root" window for transparency effects instead of properly understanding and using how the windows are layered on the display.
The new WM which is being developed to replace Fluxbox within Lumina will provide compositing as well so this will no longer be an issue. In the meantime, you might be able to install/provide another stand-alone compositor which you can setup to autostart in the background in order to support active transparency effects between windows (such as xcompmgr).

**Comment by william-os4y** [comment]
I'm doing it with xcompmgr.

Sad to read that Fluxbox is just temporary because tabbing feature, apps
config file and keys config files provide lot of great features.
