### ISSUE TITLE
lumina(BSD) based on Qt gui toolkit(LGPL). It could have been based on  EFL Gui toolkit(BSD)

### ISSUE THREAD

**Issue by zaxebo1** [pcbsd/lumina#131]
(This is not a bug/issue in the sense of code, but this can be considered a licensing bug/licensing issue; hence i am filing this github issue)

lumina desktop is going to be BSD licensed, but it depends **upon Qt which is LGPL**

enlightment desktop (see https://en.wikipedia.org/wiki/Enlightenment_%28software%29 ) is alreayd BSD licensed, which uses Enlightment Foundation library ( https://en.wikipedia.org/wiki/Enlightenment_Foundation_Libraries )GUI toolkit. Note that EFL library is also BSD licensed.  Englightment desktop already implemented on top of EFL shows that EFL is a capable toolkit.

****

may be , if lumina desktop (BSD) was developed on top of EFL GUI toolkit(BSD licensed), instead of Qt(LGPL licensed), then the entire stack of PC-BSD(BSD licensed) would have become BSD licensed stack.

**Comment by zaxebo1** [comment]
in my humble optinion
the reason of switching from gcc compilation to clang compilation of freebsd was that the entire foundation stack will become BSD. In the same way, probably it would have been important for PC-BSD community for create the desktop on top of full BSD stack

**Comment by beanpole135** [comment]
Actually, LGPL/BSD licensing for the graphics stack is of less importance to me than reliability, FreeBSD support, documentation, technologies available (network/file IO, multimedia support, etc...), and project support (bugfixes, updates, other maintenance stuff). By using Qt instead of EFL for the graphics toolkit for Lumina, I am guaranteed all of these things, while EFL is unmaintained and out of date on FreeBSD (so the developers seem to use it on Linux/Other - possibly causing other issues down the road).

While it would be nice to have a BSD-licensed graphics stack for Lumina, I would prefer to have something that works reliably on FreeBSD for the foreseeable future instead.
