### ISSUE TITLE
QMediaPlayer missing, despite Qt Multimedia being installed

### ISSUE THREAD

**Issue by fusion809** [pcbsd/lumina#164]
Hi,

I ran:

```sh
qmake && make
```

from the source code directory of Lumina version 0.8.7 but it gave the error:
```sh
LuminaXDG.cpp:11:24: fatal error: QMediaPlayer: No such file or directory
 #include <QMediaPlayer>
                        ^
compilation terminated.
Makefile:271: recipe for target 'LuminaXDG.o' failed
make[1]: *** [LuminaXDG.o] Error 1
make[1]: Leaving directory '/home/fusion809/Programs/lumina-0.8.7-Release/libLumina'
Makefile:48: recipe for target 'sub-libLumina-make_default' failed
make: *** [sub-libLumina-make_default] Error 2
```

OS: Sabayon Linux 64-bit. I installed Qt Multimedia 5.4.2 with Entropy (the package manager of Sabayon). 

Thanks for your time,
Brenton

**Comment by vovd** [comment]
Have you installed the Dev package ?

**Comment by beanpole135** [comment]
As vovd alluded to, that sounds like the Qt Multimedia package you installed did not include all the Qt modules/files necessary to build a Qt5 application (the "QMediaPlayer" class has existed in the "multimedia" build module for Qt5 since version 5.0).

The other possibility is that the "qmake" you are running is the Qt4 version, not the Qt5 version (in which case the "multimedia" module does not exist). On FreeBSD systems, the Qt5 version of qmake is found in /usr/local/lib/qt5/bin/qt5 (which is not in the standard binary search paths), so it might be something similar on Sabayon Linux.

**Comment by beanpole135** [comment]
Closing ticket due to OP timeout.

**Comment by LiuLikeQian** [comment]
add the follows into the .por
QT       += core gui
QT       += multimedia
QT       += multimediawidgets
QT       += winextras
