### ISSUE TITLE
Failed to build for Ubuntu 14.04 (PPA)

### ISSUE THREAD

**Issue by Sunderland93** [pcbsd/lumina#179]
Hello. I tried to build Lumina 0.8.8 for Ubuntu 14.04 in PPA. But build failed with error:

```
make[2]: Leaving directory `/«PKGBUILDDIR»/lumina-fileinfo'
make[1]: Leaving directory `/«PKGBUILDDIR»'
   debian/rules override_dh_install
make[1]: Entering directory `/«PKGBUILDDIR»'
dh_install --list-missing
dh_install: libluminautils1 missing files (usr/lib/*/libLuminaUtils.so.1), aborting
make[1]: *** [override_dh_install] Error 20
make[1]: Leaving directory `/«PKGBUILDDIR»'
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary-arch gave error exit status 2
```

Here is a full buildlog http://pastebin.com/K6LHkUSr

**Comment by beanpole135** [comment]
Hm.. That seems like an issue with the debian/ubuntu package building instructions rather than something with the Lumina sources. In particular, it seems like the dh_install tool is looking in the wrong dir for the library (usr/lib/*/libLuminaUtils.so.1 instead of usr/lib/libLuminaUtils.so.1).

(Cleaned up install info from your log: Seems like the library did install properly)
> strip --strip-unneeded "/«PKGBUILDDIR»/debian/tmp/usr/lib/libLuminaUtils.so.1.0.0"
> ln -f -s "libLuminaUtils.so.1.0.0" "/«PKGBUILDDIR»/debian/tmp/usr/lib/libLuminaUtils.so"
> ln -f -s "libLuminaUtils.so.1.0.0" "/«PKGBUILDDIR»/debian/tmp/usr/lib/libLuminaUtils.so.1"
> ln -f -s "libLuminaUtils.so.1.0.0" "/«PKGBUILDDIR»/debian/tmp/usr/lib/libLuminaUtils.so.1.0"

**Comment by Sunderland93** [comment]
dh_install is required? I have no idea how to solve this problem

**Comment by vovd** [comment]
dh_install is a debhelper binary which is already listed in build-dependencies so you should already have it. Anyway, the PR should fix the problem.

**Comment by Sunderland93** [comment]
Thanks!
