### ISSUE TITLE
(Linux) Removing app from quicklaunch causes segfault

### ISSUE THREAD

**Issue by texstar** [pcbsd/lumina#181]
Trying to remove an app from quicklaunch causes a segfault in Lumina-DE and throws me back to the login manager.

**Comment by beanpole135** [comment]
Try to rebuild Lumina from source (master branch) and see if it works for you now. I converted a lot of the "delete" calls on widgets to use the Qt "deleteLater()" function instead, but since this issue is unreproducible on FreeBSD systems I can't be sure if this fixes the problem for you or not.

https://github.com/pcbsd/lumina/commit/b9880c772e2ffe097c54f19689f56c4606f87f85

**Comment by texstar** [comment]
Updating from git master resolves this issue. Thank you.
