### ISSUE TITLE
Tray clock size changes dynamically

### ISSUE THREAD

**Issue by larsengels** [pcbsd/lumina#187]
Using a non mono-spaced font, the  horizontal size of the clock changes every second.
To fix it, a fixed size for the clock tray container could probably used.

**Comment by larsengels** [comment]
Environment: lumina-0.8.8,1 on FreeBSD-11-CURRENT

**Comment by beanpole135** [comment]
What time format code are you using?
if you use "ss" instead of just "s", then the time string will always stay the same (pads the output with zeros). Similarly, if you display format to "Time first, then Date", you can use your date format/length to determine plugin size instead.

I do see your point however, and since the auto-resize thing comes directly from the way Qt widgets work, I will need to look into providing a work-around....  :-)

For example, my settings are:
Time: "h:mm:ss A"
Date: "M/d/yy ddd"
Format: "Time first, then Date"

**Comment by larsengels** [comment]
I'm using "hh:mm:ss". The problem is, that e.g. "0" is wider than "1" which is narrower than "2", so the clock is dancing. :)

**Comment by beanpole135** [comment]
Ok, rebuild and try it out now. I just added a smarter "minimum" size for the plugin based on the time format which seems to fix the resize issue here.

https://github.com/pcbsd/lumina/commit/b41c03fe782d3cfbab12a9f63e7053fa750f8ec1

**Comment by larsengels** [comment]
Look good now!
