### ISSUE TITLE
[Help/Maybe Issue] Kde5/LxQt not work after install lumina desktop

### ISSUE THREAD

**Issue by SunRain** [pcbsd/lumina#190]
Hi, I installed lumina follows this instruction http://lumina-desktop.org/get-lumina/#ubuntu

My desktop env is kubuntu15.10 width SDDM(no other DE, only kde5)

After installtion, lumina works well, but after login kde, I confront some problems.

I can login kde, after kde Splash Screen, desktop appeares, but whenever I click my mouse or click my keybord, the Splash Screen comes again, then screen becomes black and only the mouse pointer displayed on my blacked screen.

Here's something I tried.
I tried install LxQt, not works.
I tried to purge lumina, not works.
I tried to remove some configuration files by kde/lumina (~/.kde, some config file in  ~/.config (I may miss some configuration files)), not works
Tried to remove ~/.XAuthority files, not works
I tried install LxQt, can't login, only a dialog with message - LxQt crashed too many times -.
I tried to purge all DE related packages(kde, lxqt, lumina) and only keep xorg related packages, then reinstall kde only, not works

Here's what I found
I reinstall lumina and kde, then login lumina.
I open qterminal app, then run konsole(the kde console app) from qterminal, konsole runs, but after I  try to input some words, the first time I click my keybord konsole crashed(no special debug logs in qterminal)

I think something may conflict with kde frameworks, but I can't figure out what is really wrong.
Anyone can help me?

**Comment by beanpole135** [comment]
Well, this sounds more like a KDE5/KF5 issue rather than a Lumina issue. Since LXQt uses some of the KF5 libraries, I would not be surprised if there was something particular in the KF5  libraries which is causing the issues (maybe a conflict/issue between the KF5 library version and the current Qt5 version?).

Background:
Lumina is based on pure-Qt5 libraries, whereas KDE applications/tools use the special KDE library bundle of custom/modified Qt libraries (which provide a lot of the same functionality in different ways, but is not the same as the "pure" Qt libraries from the Qt Company) . Similarly, Lumina uses it's own distinct settings files/hierarchy and does not mix with the settings from other DE's (except for initial X session setup - that is usually handled by the login manager before any DE gets started, and Lumina just uses it as-is).
