### ISSUE TITLE
resetting multiple display settings

### ISSUE THREAD

**Issue by abelbabel** [pcbsd/lumina#200]
When I plug a second display in a laptop, I'm able to configure it via lumina settings manager (that it should be left of the laptop screen, which resolution, etc.). This setting is not preserved during reboots. I'm not sure if it even changed during re-logins. I'm currently working around this issue with a script doing some `xrandr` stuff ...

**Comment by beanpole135** [comment]
Yes, the lumina-xconfig utility is currently just a front-end to xrandr and only performs temporary X session changes (will be reset back to system settings on next X session).
There are so many different ways/standards to save/modify the X session setup on a per-user basis that I am currently going through the various specs and trying to find the best one for Lumina to standardize on. Once the new WM is implemented I am also planning to implement this X session restore functionality since Lumina will then control the whole session startup routine (without possible conflicts/infighting between other standards/formats).
