### ISSUE TITLE
problems with panel and maximized windows

### ISSUE THREAD

**Issue by abelbabel** [pcbsd/lumina#202]
I have two issues with panels and windows:

1. Some parts of a maximized window are hidden behind the panel (if it is at the bottom)

2. In multi-screen mode: When there is a single panel on one screen (at the bottom) on no panel on the other screen then maximized windows on the screen with no panel will not use the whole place of the screen, but leave some space free where on the other screen there is the panel.

**Comment by beanpole135** [comment]
1) This should already be fixed in the current 0.9.0-devel sources.
2) This is a known limitation of using Fluxbox: it only understands one of the screen reservation protocols (entire screen side - crossing any monitor boundaries), instead of also understanding the partial screen reservation protocol.
