### ISSUE TITLE
[Question]Wayland support?

### ISSUE THREAD

**Issue by Sunderland93** [pcbsd/lumina#205]
have any plans to support Wayland?

**Comment by beanpole135** [comment]
I get asked this question often enough that I should probably put it in the FAQ on the website... :-)

There are currently no concrete plans on supporting Wayland/Mir/Other graphical systems, mainly because these systems are still not available (even in a semi-functional state) on FreeBSD.
I *have* setup the Lumina source tree to be extremely easy to port to other graphical systems eventually (especially Wayland - since Qt already has support for it). All it takes is re-implementing the functions within the LuminaX11.cpp file to support the new system, and everything else should automatically start working.
