### ISSUE TITLE
Insight-FileManager.png is missing.

### ISSUE THREAD

**Issue by Pival81** [pcbsd/lumina#232]
I was trying to adapt the spec file to the latest release, because the latest version for fedora linked on the official site is outdated.
While checking the %files section for the lumina-fm, i noticed that on my local build there was no /usr/share/pixmaps/Insight-FileManager.png; at first i thought that that file was moved or deleted, but then i checked /usr/share/applications/lumina-fm.desktop and that file was listed as icon.
I even did the build two times, but it wasn't there again.
I decided to open an issue here because in the source directory, under Artworks, there is a file for that icon, so i think there is something wrong with the build process, so that it doesn't copy that file.

**Comment by beanpole135** [comment]
That missing icon was fixed in the source tree a while back (0.9.1-devel I am pretty sure). You can see the icon install definition within src-qt5/desktop-utils/lumina-fm/lumina-fm.pro
I will be generating another point release here soon though if you just want to wait for that before updating the spec file.
