### ISSUE TITLE
Phonon libraries can't be found on Arch Linux

### ISSUE THREAD

**Issue by nixalot** [pcbsd/lumina#26]
I received the following error trying to build Lumina on Arch Linux.

g++ -c -pipe -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/phonon -I/usr/include/qt4 -I../libLumina -I/usr/local/include -I/usr/include/qt4/phonon_compat -I. -I. -o main.o main.cpp
In file included from main.cpp:19:0:
LSession.h:21:30: fatal error: Phonon/MediaObject: No such file or directory
 #include <Phonon/MediaObject>
                              ^
compilation terminated.
Makefile:639: recipe for target 'main.o' failed
make: *** [main.o] Error 1

The reason is that the path on Arch is /usr/include/qt4/phonon, not /usr/include/qt4/Phonon. To work around the issue I created a symlink, but that doesn't seem like the ideal solution. I haven't checked this on other Linux distros to see if the issue exists there

**Comment by ryanpcmcquen** [comment]
Here is the fix I used for the SlackBuild:
```
sed -i 's@#include\ <Phonon@#include\ <phonon@g' lumina-desktop/LSession.cpp
sed -i 's@#include\ <Phonon@#include\ <phonon@g' lumina-desktop/LSession.h
sed -i 's@#include\ <Phonon@#include\ <phonon@g' lumina-fm/MainUI.h
sed -i 's@#include\ <Phonon@#include\ <phonon@g' lumina-fm/BackgroundWorker.cpp
```
http://slackbuilds.org/cgit/slackbuilds/tree/desktop/lumina/lumina.SlackBuild?id=e06670b2dcd55e237a21da841da193cc9f82fb91

**Comment by beanpole135** [comment]
FYI: The current version of the source tree is Qt5 based now and does not have/use phonon anymore.

The Qt4 tree is being preserved in the (static) qt4/0.7.2 branch of the repository for legacy purposes, but you might want to look into updating your build script to function with the Qt5 sources (the master branch), since that is the only branch getting updates.

The first official release of the Qt5 version (0.8.0) will probably be happening soon, I just have a couple last XCB/WM bugs I want to fix first (mostly regarding reserved screen space for panels).
