### ISSUE TITLE
File defauts is limited to a list

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#50]
In Desktop configuration, tab Aplications, we can define our best application for Web browser, Email client, file manager and virtual terminal. 
Imagine I select for my virtual Terminal an application from the proposed list. 
After a while, if I would associate Virtual terminal to the application xterm. it's not possible :-(
Indeed, xterm is not in the proposed list; and we cannot associate a exe from the filesystem on this screen.
How to proceed ?

ps:
I've added comments on the crash issue #47

**Comment by beanpole135** [comment]
Sounds like your installation of xterm did not register itself with a shortcut in /usr/local/share/applications/<xterm.desktop on FreeBSD>, this seem like a problem with how the OpenBSD port performed the installation, since the FreeBSD port just copies the shortcut from the xterm project itself into the proper directory on the system[1].

With all that out of the way, I do see your point that you can't "clear" the application registration back to the default value through the interface. Sounds like I need to make the application-selection dialog a bit smarter by adding the options to clear a setting or select a binary instead.....

[1] https://github.com/pcbsd/freebsd-ports/blob/master/x11/xterm/Makefile (look at the post-install section).

**Comment by william-os4y** [comment]
Maybe a problem linked to OpenBSD.
In fact, xterm is part of the base packages and no entries in /user/local/share/applications. 
But, rxvt-unicode does neither create entries in /user/local/share/applications. 

Sounds that even in Freebsd rxvt-unicode will never appears in the such folder
https://github.com/pcbsd/freebsd-ports/blob/master/x11/rxvt-unicode/Makefile

Note: the tips via the config file works great. 
Maybe a button to reset to default could be enough.

**Comment by beanpole135** [comment]
Yeah, FreeBSD generally only copies that *.desktop shortcut if it exists in the project's source tree itself. PC-BSD actually creates and installs those shortcuts for particular applications through their PBI system[1]  (pkg overlay with all sorts of additional information, such as adding shortcuts for apps that are missing them).

I am actually a big swamped with some PC-BSD work right now, so since the manual change for the settings worked well enough I am going to put the additional "reset" functionality for lumina-config on the back-burner for the next couple days. I will let you know on here when it is ready for you to test.

[1] https://github.com/pcbsd/pcbsd/tree/master/pbi-modules/x11/rxvt-unicode/xdg-desktop

**Comment by beanpole135** [comment]
Ok, I just put a "Reset to Defaults" option on those application registrations. Check it out and see if that works for you now... :-)

**Comment by william-os4y** [comment]
indeed, works fine. 
selecting an application not in the proposed list is not really an issue, but more a new feature. Thus not relevant here.
