### ISSUE TITLE
I don't have messagecenter in the list of desktop plugins

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#53]
I see in the sources the following desktop plugin desktop-plugins/messagecenter. 
I would use it, but how ?
Why it is not present in the list of plugin ?
Did I miss something in the compilation phase ?

Thanks

(I'm on Openbsd current 21/02/2015 and sync with github)

**Comment by beanpole135** [comment]
This is normal. The "messagecenter" plugin is not complete, and as such is not included in the build yet. That was actually the plugin where I was experimenting with a DBUS notification watcher, but since that did not work out I am going to be converting it into a display for the Lumina messaging system once I get that system finalized and implemented.
