### ISSUE TITLE
lumina-open does not prompt when exit status is >0

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#55]
Don't know if this is a real issue, but I've added in ~/Desktop a shell script. 
When this one fails (exit >0) lumina-open does not report it. 
I've saw in the code that the return code is well known but not used. 
By doing this in lumina-open/main.cpp, I had my epxected result:
   //if(retcode!=0 ){
-  if(p->exitStatus() == QProcess::CrashExit){
+  if(p->exitStatus() == QProcess::CrashExit or retcode> 0 ){
     qDebug() << "[lumina-open] Application Error:" << retcode;

**Comment by beanpole135** [comment]
This is actually by design. 
Lumina-open used to just compare the exit code and look for non-zero to display the crash handler, but then I discovered that *tons* of applications do not respect the conventions and return 0 for normal exits. So I opted to have it operate more conservatively and only show the crash handler for an application that *truly* crashed instead of having pop-up dialogs all over the place.
