### ISSUE TITLE
new feature: would it be possible do select/change the icons on the desktopview plugin

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#56]
In fact, I'm using often couple of shell scripts . So I've placed them in ~/Desktop and I double click on them when needed. 
To better identify them, I would have the possibility to assing different icon to each of them. 
Does this is a feature I've missed somewhere ?

Thanks

**Comment by beanpole135** [comment]
You just need to give it an "Icon=" line in your *.desktop file.

For example: "Icon=view-task-child" will use the "view-task-child.png" image from the current Icon theme. You can look through the available icons in /usr/local/share/icons/<icon theme>/<size>/<category>/<name>.

**Comment by william-os4y** [comment]
OK. Thanks. 

Where should I put the .desktop you are talking about ?
Let's say I have ~/Desktop/script1.sh and ~/Desktop/script2.sh. 
How can I assign 2 different icons ? 
Should I build ~/Desktop/script1.desktop and  ~/Desktop/script2.desktop ?

**Comment by mike-pt** [comment]
If I may add an opinion I would put the .sh file elewhere (maybe just you're home, home ~/scripts ?)

And then put the .desktop files in "~/Desktop" and yes you can assingn a diferent icon even if pointing to the same Exec file...

Example, I have "xvt" installed and just ln the .desktop file for /usr/local/share/applications:
% ll |g xvt
lrwxr-xr-x  1 miguelc  miguelc    41B Feb 23 18:08 xvt.desktop -> /usr/local/share/applications/xvt.desktop


And then I can simply clone it and change the icon or something else... but note both point to the same in Exec.


[miguelc@r2d2:~/Desktop ]% cat xvt.desktop 
```
[Desktop Entry]
Type=Application
Version=1.0
Name=xvt
GenericName=xvt terminal emulator
Comment=xvt terminal emulator
Icon=/usr/local/share/pixmaps/xvt.png
Exec=xvt
Categories=GNOME;X-XFCE;X-Xfce-Toplevel;System;Utility;TerminalEmulator;
StartupNotify=false
```
[miguelc@r2d2:~/Desktop ]% cat xvt2.desktop                                                                      
```
[Desktop Entry]
Type=Application
Version=1.0
Name=xvt
GenericName=xvt terminal emulator
Comment=xvt terminal emulator
Icon=Terminal
Exec=xvt
Categories=GNOME;X-XFCE;X-Xfce-Toplevel;System;Utility;TerminalEmulator;
StartupNotify=false
```

"Icon=Terminal" just uses the "terminal" icon provided by the theme, much like @beanpole135 explained above 

Hope this helps

**Comment by william-os4y** [comment]
Thanks mike-pt. I understand better now. 
In short what I'm looking for is a kind of ".desktop creator".

**Comment by beanpole135** [comment]
There might be a couple *.desktop file creators around, but I can't think of any offhand. The spec is not that complicated, and there is a link to the example page within the spec sheet (if you want to browse back through the different sections for additional information).

http://standards.freedesktop.org/desktop-entry-spec/latest/apa.html

**Comment by william-os4y** [comment]
I've not found one written wih Qt. In fact it should not be too difficult to build one like the "Launcher" in xfce. 
I've try it, and GUI is done :). This is the easy part. 
Unfortunately, the Qsettings objects sounds to not able to manage the .desktop files. http://qt-project.org/forums/viewthread/14796

In fact to read .dektop file Lumina is not using Qsettings either. 

Maybe I should map it to XDGDesktop and write a "saveDesktopFile" ?

What do you think ?

**Comment by beanpole135** [comment]
If you are going to submit your *.desktop creator to be included with Lumina, I would recommend using the libLumina/[LuminaXDG | LuminaUtils] functions to simplify all the backend functionality. For example, you could use the XDGDesktop class as your data storage container, then just write an extension for it which converts it back into a file format (a QStringList with one line per entry), then use LUtils::writeFile() to save the actual file. The only thing you need to be vary careful about with the XDGDesktop class is that when it is filled from a *.desktop file, it is a filtered version of the full information contained in that file (for localization purposes especially, and the special "action" framework is also not used/implemented yet). So if you are trying to create a new *.desktop entry it will work fine, but for editing a current entry it might not be the best choice.

**Comment by william-os4y** [comment]
I'll try. But my time is quite limited ... it can take weeks

**Comment by william-os4y** [comment]
I've just published the 1st release of the desktop editor for lumina. 
some todo to still finalise. 

details are here:
https://github.com/william-os4y/lumina/commit/e4b165ed24840e1cc24c45b328a6d2965630cad4

Comments/feedbacks are welcome

**Comment by william-os4y** [comment]
I've pushed some changes.

branch is here  https://github.com/william-os4y/lumina/commits/deskEditor

any feedbacks ?

**Comment by beanpole135** [comment]
Ok, I finally got some time to look this over (at a conference in Tokyo at the moment). My first impressions are that it is coming along really well, it just needs a bit of cleanup and final touches. Here are a few things I noticed - most of them are just small little things which are easy to change. It is looking good!

1) General layout is good but you do have quite a bit of "dead" space at the top and bottom of the window. You might want to decrease the default window size and adjust the spacers a bit (I would recommend a single spacer between the "run in terminal" and "cancel/apply" buttons instead of one each at the top/bottom of the window).
2) You are missing icons on the two file retrieval buttons (might want to add tooltips or status text on them as well so that people know what it does before they click on it).
3) Spelling error: "stratup notification" -> "startup notification"
4) When saving the "Type" of the shortcut in the file, make sure to use "Application" instead of "application". While the upper/lowercase difference does not make a difference in Lumina, it might cause problems in other DE's since the standards use an uppercase "A". 
5) I like that you don't change any localized values in the file when saving your changes, but if the base/non-localized value gets changed you should probably remove all the localized values as well (otherwise the localized version won't match up with the new non-localized version).
For example: If I load a file with a ton of translated "Name=" lines ("Name[<locale code>]="), those localized lines should be removed if I changed the generic Name value from what it was previously - otherwise the user might not actually see the name change because it will use the old localized value instead of the new generic value.
6) When you cancel the icon selection window - it actually removes the current icon. I think the QFileDialog class has an optional boolian which you can pass to it which lets you know afterwards if the user cancelled the dialog instead of selecting something.
7) I am not sure what it is causing this, but every time I open one of the file selection dialogs (icon, exec, or path selection dialogs) I always start out in a different directory. You might what to put in particular places to start for each button (LOS::AppPrefix()+"/share/icons" for the icon selection dialog for instance, LOS::AppPrefix()+"/bin" for the Exec selection, etc...)
8) Finally, just add a window icon and title to the Qt window so that it shows up on the task manager properly.... :-)

Good work!

**Comment by william-os4y** [comment]
Thanks for the feedback. 
Indeed layout was not my first priority. I was just looking at functionalities.  this WE I'll check your points 4 to 7. 
Later I'll  can check layout, icons, ...

**Comment by william-os4y** [comment]
here updates:
https://github.com/william-os4y/lumina/commits/deskEditor

my comments:
1) I'm not against your idea, but as a 1st step, I propose you a better sizing. 

2) done.  As described in LXDG::FindIcon, I'm using Oxygen files

3) done. (in the .ui file) 

4) Done. 

5) still to do. You are correct !!!. But this concerns several items like Name, Comment, ... I'll check how the others are managing this. 

6) Done. 

7) not corrected. In fact, I'm showing the directory where you were. For example for an icon in /usr/local/share/icons/oxygen/apps/hello.png, I'll open you in /usr/local/share/icons/oxygen/apps. 
Same concept for WorkingDir and Command. 
Is there an another problem ?

8) Done.


What about naming convention ? name of button, specific methods, ... 
where should I install the config files (desktop-app.template and desktop-link.template) ?

Thanks

**Comment by beanpole135** [comment]
7) I was referring to the case where there is nothing currently selected (such as an empty Path). What I was seeing was that if I clicked on the icon button - it took me where the icon was located (that is fine) but if I then clicked on the path button (with no path selected), it opened the icon directory again (same with the exec button if no exec currently). I think you just need an additional  check for an empty value and put in some default location for each button in that case.


Regarding the template files, depending on how you use them (read only, copy, modify, etc..) you might be able to place them into the Qt resource system (compiling them into the binary itself), and just using them from there instead of worrying about file locations on the system.
You just need to add a Qt Resource file (*.qrc) to the project and add the files to there. Then in your code you prepend the file location with a colon (":") to indicate looking in the resources (it is really easy to manage resources through the Qt Designer UI). 
For example: if the file is located in "<source base>/templates/mytemplate.template" you would open the resource ":/templates/mytemplate.template" within your code. You just can't make changes to a Qt resource, but it should work fine for just reading a template file into memory before making changed and saving it elsewhere.

**Comment by william-os4y** [comment]
I've just pushed a fix concerning the point 7) here above. 

Concerning the desktop.template files ... 
Thanks for the feedback. Thus I include my proposed template in the binary. But I would allow to users to "play with it". Thus following you, where to push them: in .lumina ? in .lumina/LuminaDE ? in .config ? ... ?

I must still work on 5).

**Comment by beanpole135** [comment]
If you want users to be able to change the default template file, then I would save it into the binary through the resource system (as mentioned before), then on application start check if a local template file exists ("~/.lumina/desktop.template" should work fine) and copy the file from the resources to the local location as necessary. This way you can always guarantee that the template file is available on disk (since you put it there on app startup if it is missing), and that the user is able to modify it since it is within the user's home directory (so every user can have their own copy of that template).

**Comment by william-os4y** [comment]
I'm nearly there:
https://github.com/william-os4y/lumina/tree/deskEditor/desktop-editor

But what could be the name of this application ?

**Comment by beanpole135** [comment]
Hum... how about "lumina-fileinfo"?
I try to keep the names somewhat descriptive of what the utility is/does, and I can foresee adding some more to this utility so that it can view a file's "properties" in addition to providing the ability to edit it's settings (if a *.desktop shortcut). This will make it a much better multi-tasker down the road.

**Comment by william-os4y** [comment]
OK. I'll send a pull-request as soon as I have adapted the code to that name. 
Thanks

**Comment by william-os4y** [comment]
I've made several changes during last week. you can find them here:
https://github.com/william-os4y/lumina/commits/deskEditor

I'll not push it as a "pullrequest" until you give me your "go".

**Comment by beanpole135** [comment]
I will take a look at it here soon and let you know. I am a bit swamped with PC-BSD work at the moment, but I think I have an open time slot tomorrow to look through this and see if it it ready.

**Comment by beanpole135** [comment]
Ok, I was actually able to make some time sooner than I thought, and I only have a couple recommendations. These are both minor and you could send in a pull request to include it in the main Lumina repo whenever you feel ready.

1) dialog.cpp -> line 121
Instead of QPixmap(DF.icon), use LXDG::findIcon(DF.icon,"") since the icon listed does *not* necessary have a full/relative path included in the file. The LXDE routine should parse it out and handle all those other cases - finding the icon on the system if possible.

2) dialog.cpp ->lines 140 and 142
The "~" abbreviation is a shell shortcut for the user's home dir and does not work in C++/Qt. You should use QDir::homePath() instead.

Overall, it is looking really good! Thanks for working on it!
