### ISSUE TITLE
LXDG::loadDesktopFile does not take "Path" into account

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#60]
Following the specifications, Path is "If entry is of type Application, the working directory to run the program in."
http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html

This parameter could be useful in some cases.

**Comment by beanpole135** [comment]
Good Catch!
It looks like the line to save the "Path" value into the data structure was simple missed - since lumina-open and other functions were already setup to take the custom path into consideration if necessary.

Fixed!
https://github.com/pcbsd/lumina/commit/7a714cdb106866e3f239d3f5776d23f4d35827ea
