### ISSUE TITLE
compilation problem due to LXDG::findAvailableAppsForMime

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#62]
On a scratch machine (opebsd-current), I cannot compile Lumina due to an LD error on LXDG::findAvailableAppsForMime. 
AS workaround I do a make install; make; make install and it works.

**Comment by beanpole135** [comment]
This is expected. Anytime you rebuild from source I highly recommend that you always rebuild/reinstall the Lumina library first. Very often new functions are added to the library at the same time that new features are enabled in the desktop/utilities - so you always want to make sure that all your compilations are performed with the most current version of the library available.

**Comment by william-os4y** [comment]
I think we are not on the same line.

I'm talking about a fresh compile process following the readme and you are talking about a rebuild.

**Comment by beanpole135** [comment]
Was this a fresh checkout of the source on a system without Lumina, or did you have an older version of libLumina on the system? I still see an occasional issue where the linker uses the current version of the library on the system (the older version) instead of the newly compiled version of the library in the source tree. Usually just running "make install" on the entire project instead of "make" and then "make install" seperately will ensure that each of the pieces of Lumina gets built/installed in the proper order (library first). Otherwise you can build/install the library separately beforehand (cd libLumina; make; sudo make install) and that will have the same effect.

**Comment by william-os4y** [comment]
If you cannot reproduce it, it's maybe an error on my side. I'll do it later and note carefuly what I do.
