### ISSUE TITLE
Sound is not working on OpenBSD

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#69]
Not sure this is a Lumina issue, but maybe someone here can help me. 

The login and logout songs are not working. The ausio plugin is neither working. 
No crash, ... but no sounds. 

This is maybe linked to a sound's backend not present on OpenBSD. 

Nevertheless following QT doc Gstreamer should work. 
On my machine the following packages are installed:
gstreamer1-1.4.5    framework for streaming media
gstreamer1-plugins-base-1.4.5 base elements for GStreamer
gstreamer1-plugins-good-1.4.5p0 good elements for GStreamer

**Comment by beanpole135** [comment]
I am actually still running into this on FreeBSD as well - just trying to find the right gstreamer plugin so it starts working out of box. Try installing the gstreamer1-plugins-soup plugin (loading files as URL's) - so far I am narrowing down on that one because it seems like whenever it works on my system is when I have that plugin available after installing the "pithos" utility (but I have not verified that plugin is the missing piece yet).

**Comment by william-os4y** [comment]
I've install all available plugins in OpenBSD (http://openports.se/multimedia/gstreamer1). 
I've installa the mm package and recompile the whole lumina src
Problem not solved.

**Comment by beanpole135** [comment]
I just browsed your OpenBSD ports collection on that site, and found one that looks promising: "multimedia/qt-gstreamer"[1]. Do you think that will help? The problem is that Qt cannot see/use the gstreamer backend you have right now - usually meaning that something is missing in the Qt or gstreamer installation.

[1] http://openports.se/multimedia/qt-gstreamer

**Comment by william-os4y** [comment]
Sorry for delay.

Sure I can check.
I'll try to use some of the samples provided.

**Comment by beanpole135** [comment]
Just to follow up with this: I think I finally tracked down which plugins/ports are required to get audio support working on FreeBSD:
gstreamer-plugins-[ogg, vorbis, core] seem to be required, although the "core" port is still a collection of a number of other ports (have not determined which port within there is needed yet).  Note that this is still the older gstreamer plugins (not the gstreamer1-* ports), but that might be a Qt porting setting for Qt on FreeBSD specifically.

How I figured this out was by installing the ogg plugin (since Lumina uses *.ogg files for the login/out chimes), then looked at the ~/.lumina/logs/runtime.log file right after login to see what error(s) Qt/gstreamer was listing when trying to play the chimes. Then I gradually installed the plugins necessary to fix the errors.

I hope this helps!

**Comment by william-os4y** [comment]
I've re-install whole machine to openbsd-current. 
Last commit of Lumina
But, does not wrk. 
I've got this in runtime.log

Warning: defaultServiceProvider::requestService(): no service found for - "org.q
t-project.qt.mediaplayer"

**Comment by beanpole135** [comment]
That definitely sounds like your version of Qt is not setup for multimedia support.
On FreeBSD we use the multimedia/qt5-multimedia port[1], which appears to set a couple build-time environment variables for Qt depending on the audio system backend which is setup (gstreamer by default). Perhaps there is something missing in the OpenBSD port for Qt so that this is configured?

[1] http://www.freshports.org/multimedia/qt5-multimedia

**Comment by william-os4y** [comment]
since the last release (April, 14th) I have the following message:
"
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
"
What does this means ?

**Comment by beanpole135** [comment]
the "pa_*" error is something related to PulseAudio (pa) usually. That sounds like your version of Qt is configured to use the PulseAudio sound system backend instead of whatever is actually on your system.

**Comment by william-os4y** [comment]
QT5 is compiled with Gstreamer1, not Gstreamer0.10.
http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/x11/qt5/Makefile?rev=1.24&content-type=text/x-cvsweb-markup


By starting DBUS, I'm able to no more get the popup with the message (cfr 2 days ago). But I still don't have sound. 
QT5 is quite new to OpenBSD, so I'm not sure the problem is coming from Lumina. 
I'll look for very simple sample of QT5 source code to assure that QT5 on Openbsd is correctly working. 

I propose to close the issue. 
In any case, I could open a new one, later, with much more details.

**Comment by beanpole135** [comment]
Sounds good. 
Let me know if you want me to throw together a quick QtMultimedia sample application for you. I have a simple example of this in the lumina-desktop/LSession.cpp file if you want to just pull that out and place it within it's own small utility (look at the "playAudioFile(QString filepath)" function starting at line 470).
