### ISSUE TITLE
Taskmanager does not display the window's title of xterm

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#70]
If you have several xterm windows, the taskManager does not display their window titles. Even if you start it with -title: "xterm -title hello" or via the echo -n "\033]2;${USER}@${HOST}: ${PWD}\007"

I've tried rxvt: "rxvt -name hello". 

I've tried mlterm: "mlterm -T hello"

None are working. Why ?
Does this is a problem with the terminal application or with Lumina ?

**Comment by beanpole135** [comment]
I am still not sure.
Lumina will actually try four different methods of getting that window information, moving to the next one if the current method/atom does not have any information to display:
1) _NET_WM_VISIBLE_ICON_NAME
2) _NET_WM_ICON_NAME
3) _NET_WM_VISIBLE_NAME
4) _NET_WM_NAME

It looks like XTerm does not supply that information (other terminal applications do), instead it uses the old standards of "WM_NAME" and "WM_ICON_NAME" for saving that information. I still need to implement the search/use of these old standards within the new  XCB backend for Lumina so that it has better backwards compatibility with the old standards, but once that gets put in, then the xterm titles should appear.

**Comment by beanpole135** [comment]
Fixed!
Now it will use the WM_NAME and WM_ICON_NAME values as additional fallback routines when fetching the title for a window. (This *does* fix the xterm issue mentioned above - I am running it here).

**Comment by william-os4y** [comment]
Works very good. 

For those who want to know how to do it. Here just an example: echo -n "\033]0;${USER}@${HOST}: ${PWD}\007"

Details here: http://tldp.org/HOWTO/Xterm-Title.html
