### ISSUE TITLE
Task manager display/hide a window

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#71]
WHen I have several instances of the same application, the Taskmanager combine them into one. 
We can click on this common icon I see the different instances. 
When I click on one of those instances we can display/hide the corresponding window. Fine. 

When I have only 1 instance of a specific application, clicking on it just display it. the toggle display/hide is no more working. 

Does this is a normal behaviour ?

**Comment by beanpole135** [comment]
No, somthing just broke recently where the first time you click on a window it is not properly detecting the state of the window - causing it to bring it forward instead of hide it. However, I have noticed that if you try clicking the button a few times will eventually hide the window. This seems to imply a timing or flag issue within the button itself which I am still trying to figure out. In the meantime, just right-click on the button and select the appropriate action from the list instead. That will always work.... :-)

**Comment by beanpole135** [comment]
Just following up with this: it has been fixed in Lumina 0.8.4-release

**Comment by william-os4y** [comment]
Indeed, with the code of today (April 26th) I confirm it works on OpenBSD too. 
Many thanks
