### ISSUE TITLE
Request feedback: add filesystem capacity in statusbar

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#73]
Since couple of days I'm adding a feature I like with Thumar: display of relevant info in the status bar (number of items and files' size). 

My request here is just to know if you are interested with the following code working to display the capacity of each filesystem visited. 
https://github.com/william-os4y/lumina/commit/bd557d962fa83b9fb7638d49c1ae2cdbc8508d7c

If yes, then I will put the 3 command's lines in LOS; and will propose a "pullrequest"

**Comment by beanpole135** [comment]
I think this is a really good idea. 

If you want to get that ready for a pull request, I only have a couple recommendations as you work on this:
1) Put the OS-specific ("df" utility usage) in LOS as you already mentioned. (If you want me to do this, just let me know)
2) Put the OS-specific routine usage into the "BackgroundWorker" class in lumina-fm, since querying disk space *can* take a bit of time on some systems.
3) Only run the directory capacity routine on user-modifiable directories, and then place the notice in the "ui->label_dir_stats" widget (where the "Limited Access Directory" notification is shown for non-user directories). The status bar is typically used for short/temporary messages, and I would like to put some file-specific info there when the user mouses over particular files here in the near future.

**Comment by william-os4y** [comment]
No problems to do that. 
concering 1), I've just pushed it on my branch "fmNumbers"
Concerning 2), I have some difficulties on how to do it. Ideally, I would use a sample. But I don't find them. Does the "mount" command should not be threaded too ? With NFS fielsystem in troubles, I think the mount command can take lot of time (until timeout of NFS I think). 
Concernign 3), up to you. I don't think that file size, ... are so important. They can be erased by an another message.

**Comment by beanpole135** [comment]
2) You just need to define a new signal in the background worker class (something like DirInfoAvailable(QString)), and then in the startDirChecks() function add your info routine right before the ZFS snapshots search routine which emits that signal when possible. Then in the mainUI class create a new slot which is connected to that signal and simply displays the given string in the proper location.
3) That is fine then, with the signal/slot method above it only takes a single-line change to switch which UI element to show the string. This lets us easily experiment with different display implementations and figure out which one seems to work best.

**Comment by william-os4y** [comment]
I've just ushed the modifications 
https://github.com/william-os4y/lumina/tree/fmNumbers

It works, but I'm not sure I did it correctly (with threads).

**Comment by beanpole135** [comment]
It mostly looks good, I see a few things that could be streamlined, but overall it looks fine for now. I am actually have a couple other things in lumina-fm to streamline as well, so if you go ahead and send in a pull request, I will merge this into the main repo and do all of the changes/updates at the same time.

**Comment by william-os4y** [comment]
done

**Comment by beanpole135** [comment]
Thanks for sending that in!
I will get started on some of the streamlining here tonight/tomorrow then.
