### ISSUE TITLE
new request for lumina-search

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#75]
1) would be great to have different "set" of search. Each having a name.
For example, the set called "home" will look in /home/wi and exclude /home/wi/nas (which is a symbolic link to my nas). 
the set called "mnt" will look in to /mnt (no excluded folders). 
the set called "nas" will look in /net (no excluded folders)
Each of those parameters would be saved in .lumine/LuminaDE/lumine-search.conf
One of those "set" will be the default one. This will be the set of parameters used in case the user does not provide a set's name. 

2) via command line the user could type: lumine-search -sets nas <files to search>
And the application will immediately start the gui and show the results. 

3) for each sets, the Insight File manager will have a menu entry. This will display the gui with the parameters associated to the set. 

Those ideas come because I do often the same type of search: on shared drive, on local docments, on /usr. 

What do you think ?

**Comment by beanpole135** [comment]
That sounds completely reasonable.
The most complicated thing about this is to abstract out the method of saving "sets" of search parameters/profiles so different utilities can easily access it, but even that is not too difficult.

Actually, I think I just came up with something a bit simpler/easier to implement.
Observation) The main thing that is important is the starting directory for the search (home dir, /mnt, other...). The "excluded" directories are already set to full paths, so there is no need to change/modify the excludes (except for maybe an option to disable any excludes temporarily) since it will only be excluded if that dir is a sub-directory of the search start point.

Solution) 
1) Add 3 new CLI flags to lumina-search:
  "-dir <path to dir>": Start file search in this directory
  "-no-excludes": Do not apply directory exclusions to the given search.
  "<search term>": Option to specify an initial search term and start the search from the CLI

2) Have lumina-fm provide a couple ways to start searches.
 - "Quick Search" menu for starting searches in any bookmarked directory
 - "In-Line Search" for starting a search in the currently-viewed directory.

This prevent issues with modifying config files across multiple utilities, while allowing a flexible framework for any user/application to integrate with lumina-search in an application-specific way (allowing the re-use of current settings like bookmarks).

Thoughts?

**Comment by william-os4y** [comment]
I think that QSettings should manage the read/save of all parameters. 

CLI is not a big deal to develop.

To my eyes there is only 1 search system: lumina-search. It's just that Insight-fm has direct acces to it (via menus).
In-line search is not part of this request. Such search facilities could be part of 2nd improvement request. 
A feature I like in file mnager is the filter system. I think It corresponds to what you call in-line search. 
I short, this feature allow the user to display the files based on glob like pattern. For example: "lumina*", "*.pdf",  "*.cpp", "lumina*.cpp", ...


Thus 2 differents systems. One is real search, the other is much more a filtering tool.

**Comment by beanpole135** [comment]
Ah, we are simply talking about different things for "in-line" searches - I probably should have used a different term... :-)

I was talking about more than just a filter for the current dir contents, but the full recursive file/dir search (through lumina-search) simply being started in the current dir. The "filter" method is semi-supported through Qt right now, you just need to start typing the name of a file and the widget will automatically take you to the first file/dir which starts with it. So it doesn't actually "filter" the contents, but simply provides a shortcut to finding something. For a full "filtering" system we would need to write a completely new routine/functionality for the file manager - which I don't have any plans for at the moment but might be nice to implement sometime down the road.

**Comment by william-os4y** [comment]
That's done. 
I propose you the code here: https://github.com/william-os4y/lumina/commits/search

In short, this allow the user to select a "SetName" before applying the search. 
The SetName is composed of the StartDir and the ExcludedDirs. 

By default the "Default" SetName is selected. This allow backward functionalities. 

The SetName can be added/removed/modified. 

Those data are stored in aJsonFile called lumina-search.settings and is editable (text file). 
In case you prefer to edit it manually this config file, a simple parsing has been implemented showing you (on the console) where the problems are in your settings file. 

The CLI functionalities have been implemented too. Parameters are:
- lumina-search -setname <you set name> [<search word>]. 
Search word is optional. If not provided the gui will be showed to the user pre-load with the correct StartDir and ExcludedDirs. 
In case the seach wrod is add, lumina-search will automatically start the search and present the results

- lumina-search -app <search word>
This search in the application for the given word.  


Next steps:
- understand why on line 61 of ConfigUI.cpp is not working like expected.

**Comment by beanpole135** [comment]
Just hold off on this for a little bit.
I have a very particular way of implementing this type of search that I am working on pushing up to GitHub in the next couple days. My improvments do not touch any of the configuration UI stuff, so you might be able to re-apply most of your changes on top of mine if necessary.

**Comment by beanpole135** [comment]
Ok, I just pushed up my new changes to the search protocols/defaults. It does not have any concept of settings "profiles" but it does distinguish between the current defaults and temporary settings. it also allows for setting temporary values through combinations of the new input flags. 
For example:
`lumina-search -dir -search mysearchterm` -- This will start a search in the current directory for files/dirs matching "mysearchterm" (uses the default exclusions).
`lumina-search -search mysearchterm` -- This will immediately search for an application matching "mysearchterm"
`lumina-search -no-excludes -dir /mnt -search mysearchterm` -- This will immediately search the "/mnt" directory (if it exists) for items matching "mysearchterm" and will *not* use the default list of excluded directories.

I think this will help cover 90% of what you were asking for within the lumina-search utility. I just need to add support for it to lumina-fm still (it is on my list do to really soon).

**Comment by william-os4y** [comment]
If I'm not wrong your patch is just to haveCLI capabilities on the existing search system. 
Moreover I'm a little suspucious about your CLI solution; this sounds very clode to the find existing tool. Specially the search with -no-excludes. 
 
Please re-read my text of March 24. 

My approach offers much much more capabilities and CLI too. 

Let me explain it with some samples. 
I developped it because in my home directory I have different folders for different activities. For example I have some folders for my developpment (coding) activities, some for the sport activities (I'm coach of +- 20 players), ... 
By having the concept of "Sets", I'm able to select the correct folders to excuded from the search. This assure me to avoid mixing  resullts. When I search a document in my "developpment Set", I do not see results coming from my "sport Set". 
And this search can be done via the GUI and via the CLI. 

If required, feel free to ask me question regarding the "scope" or the code I propose.

**Comment by beanpole135** [comment]
Oh, I think you misunderstood why I asked you to hold off for a bit. When two people are making the same types of changes to the same file, it can get really messy both sets of changes are getting merged in. This results in all sorts of conflicts which need to be manually resolved in order to complete the merge, and I just wanted to prevent some difficulty later...

I don't think the idea of configuration "profiles" or "sets" is a bad idea at all, in fact I think that is the next logical extension for the utility if we start adding more options to the configuration tool. I was just trying to prevent a lot of duplication of work/effort between the two of us, since I noticed that you were also writing a CLI flag parser for your functionality... :-)

FYI: For your example of distinguishing between "sport" and "development" searches, can't you just start the search in the base folder for that type? You mentioned yourself that they are different directory trees within your home dir, so instead of excluding one or the other from searches, can't you just change the base directory to search?

For example, this is the way it should work right now.
1) When browsing a directory within lumina-fm, the user now has a "search" button in the File menu which launches lumina-search pre-initialized for searching with that directory as the starting point (it only searches directories contained within, not higher-level directories).
2) I am adding another button here in a moment to the User button's "Home" browser as well - making is simply to restrict your searching capabilities to the designated dir (and lower) only.

Note that these do not touch the basic functionality of running Alt-F2 or the "lumina-search" utility manually. This situation is where I could see your work coming into play by allowing the user to save commonly-used search parameters ("sets" as you call them) for easy access later on (like from a drop-down menu or ComboBox or something).

**Comment by william-os4y** [comment]
Since you have asked to hold down I've totally stopped !!!! As a confirmation of that, look at the commit's dates. 

But I stop discussion here because we are definitiveky not talking about the same features/scope.
Your changes are not addressing what I've written on March 24th.  
You have just took some words like: CLI, search in filemanager. 
I was maybe not clear enough, but you have missed to basic idea. 

.

**Comment by beanpole135** [comment]
Yeah, so I must be misunderstanding something with what you are trying to achieve. I am under the impression that these "sets" you are defining are just user-defined combinations of the configuration variables (search dir, exclude dirs) saved/organized under a unique name (instead of the current system of having a single set of default values). These user-defines sets will then be able to be created/modified/selected from within the configuration UI, and there will also be a CLI flag for automatically loading a particular "set" on initialization.
Is this correct? Is there more that your changes accomplish?

**Comment by william-os4y** [comment]
This is correct.
Thanks to this "excluded" principle, I'm able to "orient" the search and
avoid several folders of my home' directory.
I, indeed, could re-organise my folders (with soft links for example), but
thanks to the concept of "sets", I have much more flexibility (and
possibilities).
If I could stay with folder residing on my OpenBSD machine this would be
easy to re-organise folders. Problems are coming when I use my NAS. Soft
links on it is much more difficult.
That's why having different"sets" of excluded folders help me.
But, if I'm the only one seeing added value of those "sets", don't bother
you and don't complexify your code/features.
